### PR TITLE
fix: enable a11y eslint rules

### LINKED ISSUE #792: Enable A11Y eslint-rules
- Enable a11y linter rules: https://github.com/gravity-ui/eslint-config?tab=readme-ov-file#a11y and disable linter rule for the problem lines.
- Create appropriate issue for each disabled rule

### PR DESCRIPTION
**Pull request by NikitaCG**
close #792

### CODE REVIEW

File: src/sub-blocks/PriceDetailed/PriceDetails/Details/List.tsx [hunk 1]
```diff
@@ -20,6 +20,8 @@ const List = (props: ListProps) => {
         <Fragment>
             {items.map((item, id) => (
                 <div key={id} className={b('list-item')}>
+                    {/* TODO fix in https://github.com/gravity-ui/page-constructor/issues/964*/}
+                    {/* eslint-disable-next-line jsx-a11y/alt-text */}
                     <img className={b('img')} />
```
Comment (Kyzyl-ool) [inline src/sub-blocks/PriceDetailed/PriceDetails/Details/List.tsx:25]: it seems this `` tag corresponds to the mark icon (see screenshot). It plays only decorative role so we can set `alt=""`
Screenshot 2024-07-31 at 12 11 50

File: src/components/ImageBase/ImageBase.tsx [hunk 2]
```diff
@@ -14,6 +14,8 @@ export interface ImageBaseProps extends Partial<ImageObjectProps> {
 export const ImageBase = (props: ImageBaseProps) => {
     const {Image} = React.useContext(ImageContext);
 
+    // TODO fix in https://github.com/gravity-ui/page-constructor/issues/964
```
Comment (Kyzyl-ool) [inline src/components/ImageBase/ImageBase.tsx:17]: `props` has `alt` property already, so it is sufficient to disable the eslint rule

**Review by Kyzyl-ool — CHANGES_REQUESTED** [review]

File: src/sub-blocks/PriceDetailed/PriceDetails/Details/List.tsx (hunk 1 above)
Comment (NikitaCG) [reply src/sub-blocks/PriceDetailed/PriceDetails/Details/List.tsx]: done

**Review by Kyzyl-ool — APPROVED** [review]

**Review by gorgeousvlad — APPROVED** [review]
